config/routes.rb
Learn::Application.routes.draw do
  
resources :announcements
resources :navigations
resources :checks
 resources :leaves
  devise_for :users, :skip => :all

  root :to => "general#announcement"
  match "/general" => "general#announcement"
  match "/student" => "student#profile"
  post "/users/sign_in" => "sessions#create"
  match "/users/sign_out" => "sessions#destroy"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :body, :is_archived, :is_important, :is_visible, :posted_by, :title
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /announcements
  # GET /announcements.json
  def index

  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.json
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, announcement: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.json
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to @announcement, announcement: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url }
      format.json { head :no_content }
    end
  end

  def visible
    @announcement = Announcement.find(params[:id])
    @announcement.is_visible=true
    if @announcement.save
      redirect_to(:back) 
      flash[:announcement] = "Announcement Id #{params[:id]} has  been made visible"
    end
  end

  def invisible
    @announcement = Announcement.find(params[:id])
    @announcement.is_visible=false
    @announcement.is_archived=false
    if @announcement.save
      redirect_to(:back) 
      flash[:announcement] = "Announcement Id #{params[:id]} has  been made invisible"
    end
  end

  def archive
    @announcement = Announcement.find(params[:id])
    @announcement.is_archived=true
    @announcement.is_visible=false
    if @announcement.save
      redirect_to(:back) 
      flash[:announcement] = "Announcement Id #{params[:id]} has been archived"
    end
  end

  def unarchive
    @announcement = Announcement.find(params[:id])
    @announcement.is_visible=true
    @announcement.is_archived=false
    if @announcement.save
      redirect_to(:back) 
      flash[:announcement] = "Announcement Id #{params[:id]} has been non-archived"
    end
  end

    def important
    @announcement = Announcement.find(params[:id])
    @announcement.is_important=true
    if @announcement.save
      redirect_to(:back) 
    end
  end

    def notimportant
    @announcement = Announcement.find(params[:id])
    @announcement.is_important=false
    if @announcement.save
      redirect_to(:back) 
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= simple_form_for @announcement, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title, input_html: { class: 'input-block-level' } %>
  <%= f.input :body,  input_html: { class: 'input-block-level wysihtml5' }%>
  <%= f.input :posted_by %>
  <%= f.input :is_visible, input_html:{ checked: "checked"} %>
  <%= f.input :is_archived %>
  <%= f.input :is_important %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                announcements_path, :class => 'btn' %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>
<% content_for :bottom do %>
<script type="text/javascript">
  $('.wysihtml5').each(function(i, elem) {
    $(elem).wysihtml5();
  });
  $('.dropdown').hide();
</script>
<% end %>

app/views/announcements/index.html.erb
<%- model_class = Announcement -%>
<div class="page-header">
  <h1>Notice</h1>
</div> 

<%= link_to t('.new', :default => "Create New Notice"),
            new_announcement_path,
            :class => 'btn btn-large btn-success' %>
<h3>Visible Notices</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Posted By</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @announcements.each do |announcement| %>
      <% if announcement.is_visible==true && announcement.is_archived==false %>
      <tr>
        <td><%= link_to announcement.id, announcement_path(announcement) %></td>
        <td><%= announcement.title %></td>
        <td><%= announcement.posted_by %></td>
        <td><%= announcement.created_at.to_formatted_s(:long) %></td>
        <td>
          <% if announcement.is_important==false %>
          <%= link_to "Important",{:controller => :announcements, :action=> :important,  :id =>announcement.id} ,:class=> 'btn btn-mini btn-warning' %> 
          <% else %>
          <%= link_to "Not Important",{:controller => :announcements, :action=> :notimportant,  :id =>announcement.id} ,:class=> 'btn btn-mini btn-danger' %> 
          <% end %>
          <%= link_to "Invisible",{:controller => :announcements, :action=> :invisible,  :id =>announcement.id} ,:class=> 'btn btn-mini btn-inverse' %> 
          <%= link_to "Archive",{:controller => :announcements, :action=> :archive,  :id =>announcement.id} ,:class=> 'btn btn-mini btn-success' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_announcement_path(announcement), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      announcement_path(announcement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
         
          
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<!--Invisble Notices-->
<h3>Invisible Notices</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Posted By</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @announcements.each do |announcement| %>
<% if announcement.is_visible==false && announcement.is_archived==false%>
      <tr>
        <td><%= link_to announcement.id, announcement_path(announcement) %></td>
        <td><%= announcement.title %></td>
        <td><%= announcement.posted_by %></td>
        <td><%= announcement.created_at.to_formatted_s(:long) %></td>
        <td>
          <%= link_to "Visible",{:controller => :announcements, :action=> :visible,  :id =>announcement.id} ,:class=> 'btn btn-mini btn-primary' %> 
          <%= link_to "Archive",{:controller => :announcements, :action=> :archive,  :id =>announcement.id} ,:class=> 'btn btn-mini btn-success' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_announcement_path(announcement), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      announcement_path(announcement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<!--Archieved Notices-->

<h3>Archived Notices</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Posted By</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @announcements.each do |announcement| %>
      <% if announcement.is_archived==true%>
      <tr>
        <td><%= link_to announcement.id, announcement_path(announcement) %></td>
        <td><%= announcement.title %></td>
        <td><%= announcement.posted_by %></td>
        <td><%= announcement.created_at.to_formatted_s(:long) %></td>
        <td>
          <%= link_to "Invisible",{:controller => :announcements, :action=> :invisible,  :id =>announcement.id} ,:class=> 'btn btn-mini btn-inverse' %>
          <%= link_to "UnArchive",{:controller => :announcements, :action=> :unarchive,  :id =>announcement.id} ,:class=> 'btn btn-mini btn-success' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_announcement_path(announcement), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      announcement_path(announcement),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/announcements/new.html.erb
<%- model_class = Announcement -%>
<div class="page-header">
  <h1>New Notice</h1>
</div>
<%= render :partial => 'form' %>
<%= render :partial => 'form' %>
<% content_for :bottom do %>
<script type="text/javascript">
  $('.wysihtml5').each(function(i, elem) {
    $(elem).wysihtml5();
  });
  $('.dropdown').hide();
</script>
<% end %>

app/views/announcements/show.html.erb
<%- model_class = Announcement -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @announcement.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @announcement.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:posted_by) %>:</strong></dt>
  <dd><%= @announcement.posted_by %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_visible) %>:</strong></dt>
  <dd><%= @announcement.is_visible %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_archived) %>:</strong></dt>
  <dd><%= @announcement.is_archived %></dd>
  <dt><strong><%= model_class.human_attribute_name(:is_important) %>:</strong></dt>
  <dd><%= @announcement.is_important %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              announcements_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_announcement_path(@announcement), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              announcement_path(@announcement),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  <% if @announcement.is_important==false %>
    <%= link_to "Important",{:controller => :announcements, :action=> :important,  :id =>@announcement.id} ,:class=> 'btn btn btn-warning' %> 
    <% else %>
  <%= link_to "Not Important",{:controller => :announcements, :action=> :notimportant,  :id =>@announcement.id} ,:class=> 'btn btn btn-danger' %> 
  <% end %>
    <% if @announcement.is_visible==false %>
    <%= link_to "Visible",{:controller => :announcements,:action=>        :visible,  :id =>@announcement.id} ,:class=> 'btn btn btn-warning' %> 
    <% else %>
  <%= link_to "Invisible",{:controller => :announcements, :action=> :invisible,  :id =>@announcement.id} ,:class=> 'btn btn btn-inverse' %> 
  <% end %>
      <% if @announcement.is_archived==false %>
    <%= link_to "Archive",{:controller => :announcements,:action=>        :archive,  :id =>@announcement.id} ,:class=> 'btn btn btn-success' %> 
    <% else %>
  <%= link_to "Unarchive",{:controller => :announcements, :action=> :unarchive,  :id =>@announcement.id} ,:class=> 'btn btn btn-danger' %> 
  <% end %>
</div>