config/routes.rb
Learn::Application.routes.draw do
  
resources :announcements
resources :navigations
resources :checks
 resources :leaves
  devise_for :users, :skip => :all

  root :to => "general#announcement"
  match "/general" => "general#announcement"
  match "/student" => "student#profile"
  post "/users/sign_in" => "sessions#create"
  match "/users/sign_out" => "sessions#destroy"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/navigation.rb
class Navigation < ActiveRecord::Base
  attr_accessible :label, :link, :position, :role
end

app/controllers/navigations_controller.rb
class NavigationsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /navigations
  # GET /navigations.json
  def index
    @role=params[:query]
    if (@role.nil?)
      @role="General"
    end
    @navigations = Navigation.find_all_by_role(@role).sort_by{|u| u.position}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @navigations }
    end
  end

  # GET /navigations/1
  # GET /navigations/1.json
  def show
    @navigation = Navigation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @navigation }
    end
  end

  # GET /navigations/new
  # GET /navigations/new.json
  def new
    @navigation = Navigation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @navigation }
    end
  end

  # GET /navigations/1/edit
  def edit
    @navigation = Navigation.find(params[:id])
  end

  # POST /navigations
  # POST /navigations.json
  def create
    @navigation = Navigation.new(params[:navigation])

    respond_to do |format|
      if @navigation.save
        format.html { redirect_to @navigation, notice: 'Navigation was successfully created.' }
        format.json { render json: @navigation, status: :created, location: @navigation }
      else
        format.html { render action: "new" }
        format.json { render json: @navigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /navigations/1
  # PUT /navigations/1.json
  def update
    @navigation = Navigation.find(params[:id])

    respond_to do |format|
      if @navigation.update_attributes(params[:navigation])
        format.html { redirect_to @navigation, notice: 'Navigation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @navigation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /navigations/1
  # DELETE /navigations/1.json
  def destroy
    @navigation = Navigation.find(params[:id])
    @navigation.destroy

    respond_to do |format|
      format.html { redirect_to navigations_url }
      format.json { head :no_content }
    end
  end 
end

app/helpers/navigations_helper.rb
module NavigationsHelper
end

app/views/navigations/_form.html.erb
<%= simple_form_for @navigation, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :link %>
  <%= f.input :label %>
  <%= f.input :role, collection: [ "general", "student", "admin","staff",   "bitswarden"] %>
  <%= f.input :position %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                navigations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/navigations/_nav.html.erb
<div class="btn-group" style="float:right">
<% roles = ['General', 'Student', 'Admin', 'Staff', 'Bitswarden'] %>
<% roles.each do |role|%>
<% if (role==@role) %>
<%= link_to role,{:controller =>controller_name, :action=>action_name,  :query =>role},:class =>"btn btn-inverse" %>
<% else %>
<%= link_to role,{:controller =>controller_name, :action=>action_name,  :query =>role},:class =>"btn" %>
<% end %>
<% end %>
</div>

app/views/navigations/edit.html.erb
<%- model_class = Navigation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/navigations/index.html.erb
<%- model_class = Navigation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<%= link_to t('.new', :default => t("Create New Navigation")),
            new_navigation_path,
            :class => 'btn btn-large btn-success' %>
<%= render :partial => 'nav' %>

<h4>Role :<%= @role.slice(0,1).capitalize + @role.slice(1..-1) %></h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:label) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
<% @navigations.each do |navigation| %>
      <tr>
        <td><%= link_to navigation.id, navigation_path(navigation) %></td>
        <td><%= navigation.link %></td>
        <td><%= navigation.label %></td>
        <td><%= navigation.role %></td>
        <td><%= navigation.position %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_navigation_path(navigation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      navigation_path(navigation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/navigations/new.html.erb
<%- model_class = Navigation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/navigations/show.html.erb
<%- model_class = Navigation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @navigation.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:label) %>:</strong></dt>
  <dd><%= @navigation.label %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role) %>:</strong></dt>
  <dd><%= @navigation.role %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position) %>:</strong></dt>
  <dd><%= @navigation.position %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              navigations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_navigation_path(@navigation), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              navigation_path(@navigation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>