config/routes.rb
Learn::Application.routes.draw do
  
resources :announcements
resources :navigations
resources :checks
 resources :leaves
  devise_for :users, :skip => :all

  root :to => "general#announcement"
  match "/general" => "general#announcement"
  match "/student" => "student#profile"
  post "/users/sign_in" => "sessions#create"
  match "/users/sign_out" => "sessions#destroy"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/check.rb
class Check < ActiveRecord::Base
  attr_accessible :post, :title
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  # GET /checks
  # GET /checks.json
  def index
    @checks = Check.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checks }
    end
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
    @check = Check.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @check }
    end
  end

  # GET /checks/new
  # GET /checks/new.json
  def new
    @check = Check.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @check }
    end
  end

  # GET /checks/1/edit
  def edit
    @check = Check.find(params[:id])
  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(params[:check])

    respond_to do |format|
      if @check.save
        format.html { redirect_to @check, notice: 'Check was successfully created.' }
        format.json { render json: @check, status: :created, location: @check }
      else
        format.html { render action: "new" }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checks/1
  # PUT /checks/1.json
  def update
    @check = Check.find(params[:id])

    respond_to do |format|
      if @check.update_attributes(params[:check])
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check = Check.find(params[:id])
    @check.destroy

    respond_to do |format|
      format.html { redirect_to checks_url }
      format.json { head :no_content }
    end
  end
  def timepass
  end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= simple_form_for @check, :html => { :class => 'form-horizontal' } do |f| %>
<%= f.input :post %>
<%= f.input :title %>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                checks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<%- model_class = Check -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/checks/index.html.erb
<%- model_class = Check -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:post) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @checks.each do |check| %>
      <tr>
        <td><%= link_to check.id, check_path(check) %></td>
        <td><%= check.post %></td>
        <td><%= check.title %></td>
        <td><%=l check.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_check_path(check), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      check_path(check),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_check_path,
            :class => 'btn btn-primary' %>

app/views/checks/new.html.erb
<%- model_class = Check -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/checks/show.html.erb
<%- model_class = Check -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:post) %>:</strong></dt>
  <dd><%= @check.post %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @check.title %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              checks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_check_path(@check), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              check_path(@check),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/checks/timepass.html.erb
zdgfb