config/routes.rb
Learn::Application.routes.draw do
  
resources :announcements
resources :navigations
resources :checks
 resources :leaves
  devise_for :users, :skip => :all

  root :to => "general#announcement"
  match "/general" => "general#announcement"
  match "/student" => "student#profile"
  post "/users/sign_in" => "sessions#create"
  match "/users/sign_out" => "sessions#destroy"

  match ':controller(/:action(/:id))(.:format)'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    
    if user.role == "admin"
        can :manage, Admin
        can :manage, Navigation
        can :manage, Announcement
        can [:approved, :disapproved, :pending, :approve, :disapprove,:bonafidemanager ], :bonafide
    elsif user.role == "student"
        can :manage, Student
        can [ :index, :form, :status, :create ], :bonafide
        can [ :index ], :certificate
        can [:index, :result], :search
    elsif user.role == "staff"
        can :manage, Staff
        can :manage, Announcement
        can [:approved, :disapproved, :pending, :approve, :disapprove,:bonafidemanager ], :bonafide
    elsif user.role == "bitswarden"
        can :manage, Bitswarden
    elsif user.role.nil?
        can [:index, :result], :search
    end
    

    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :student, :primary_key => :student_id
  attr_accessible :area, :house, :pin, :premise, :state, :student_id, :town
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_one :user, :foreign_key => :id, :primary_key => :admin_id
  attr_accessible :admin_id, :name
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  attr_accessible :body, :is_archived, :is_important, :is_visible, :posted_by, :title
end

app/models/bitswarden.rb
class Bitswarden < ActiveRecord::Base
	has_one :user, :foreign_key => :id, :primary_key => :bitswarden_id
	has_many :hostel_wardens, :primary_key => :bitswarden_id 
  attr_accessible :bitswarden_id, :name

end

app/models/bonafide.rb
class Bonafide < ActiveRecord::Base
	belongs_to :student, :primary_key => :student_id
  attr_accessible :approved, :approved_by, :collected, :print, :reason, :student_id, :year
end

app/models/check.rb
class Check < ActiveRecord::Base
  attr_accessible :post, :title
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :student, :primary_key => :student_id
  attr_accessible :amount, :date, :reason, :student_id, :account, :total

def self.total(id)
	total=0
	 Student.find_by_student_id(id).expenses.each do |expense|
		if(expense.account=="credit")
			total= total + expense.amount
		else
			total= total - expense.amount
		end
	end
	return total
end 

end

app/models/hostel_warden.rb
class HostelWarden < ActiveRecord::Base
	belongs_to :bitswarden, :primary_key => :bitswarden_id
  attr_accessible :hostel, :bitswarden_id
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
	belongs_to :student, :primary_key => :student_id #defines primary key in student table while searching Insurance.find(2).student
  attr_accessible :amount, :edate, :password, :policyno, :sdate, :student_id
end

app/models/leave.rb
class Leave < ActiveRecord::Base
	belongs_to :student, :primary_key => :student_id #defines primary key in student table
	
  attr_accessible :approved, :consent, :end, :levaddress, :phone, :reason, :start, :student_id, :bitswarden_id
  
end

app/models/mess.rb
class Mess < ActiveRecord::Base
	belongs_to :student, :primary_key => :student_id
  attr_accessible :mess, :month, :student_id, :year
end

app/models/messoption.rb
class Messoption < ActiveRecord::Base
  attr_accessible :commentfeedback, :commentleave, :commentmess, :isfeedback, :isleave, :isopen, :month, :year
end

app/models/navigation.rb
class Navigation < ActiveRecord::Base
  attr_accessible :label, :link, :position, :role
end

app/models/option.rb
class Option < ActiveRecord::Base
  attr_accessible :option, :value
end

app/models/staff.rb
class Staff < ActiveRecord::Base
	has_one :user, :foreign_key => :id, :primary_key => :staff_id
  attr_accessible :name, :staff_id
end

app/models/student.rb
class Student < ActiveRecord::Base
	#foreign key defined here defines "defined foreign key" column in insurance table will be searched.
	has_one :insurance, :primary_key => :student_id #primary key for student table
	has_one :address, :primary_key => :student_id
	has_many :leaves, :primary_key => :student_id
	has_many :bonafides, :primary_key => :student_id
	has_many :expenses, :primary_key => :student_id
	has_one :user, :foreign_key => :username, :primary_key => :student_id#defines primary key for user table while searching Student.find(1).user
  	has_many :messes, :primary_key =>:student_id; 
  attr_accessible :bloodgroup, :college_id, :dob, :email, :feepayingP, :fname, :hostel, :mname, :mobile, :name, :pdob, :plandline, :pmail, :pmobile, :psex, :relation, :room, :sex, :student_id,:incampus,:cgpa
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :student, :primary_key => :username, :foreign_key => :student_id #defines foreign key for student table while searching User.find(1).student
  has_one :staff, :foreign_key => :staff_id
  has_one :admin, :foreign_key => :admin_id
  has_one :bitswarden, :foreign_key => :bitswarden_id
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:username

  def student?
    return role == "student"
  end

  def admin?
    return role == "admin"
  end

  def staff?
    return role == "staff"
  end

  def staff?
    return role == "staff"
  end

  def self.authenticate(username, password)
       user = User.find_for_authentication(:username => username)
       if user
         user.valid_password?(password) ? user : false
       else
         false
       end
  end
 end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/views/admin/index.html.erb
This is the dashboard for an admin

You are signed in as <%= current_user.id %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Student Welfare Department" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Student Welfare Department</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <% if user_signed_in? %>
              <li class="divider-vertical"></li>
              <li> <%=link_to "Sign Out", users_sign_out_path, :method => :delete %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
              <ul class="nav nav-tabs nav-stacked span3">
          <% if defined?(current_user.role) %>
            <% Navigation.find_all_by_role(current_user.role).sort_by{|u| u.position}.each do |navigate| %>
              <li><a href=<%= navigate.link %>><%= navigate.label%></li></a>
            <% end %>
          <% end %>
              </ul>
         
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
<%= javascript_include_tag "application" %>
   <%= yield :bottom %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learn</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/layouts/general.html.erb
<!DOCTYPE html>
<html>
<head>
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js">
</script>
  <%= stylesheet_link_tag "general", :media => "all" %>
  <%= javascript_include_tag "general" %>
  <%= csrf_meta_tags %>
</head>
<title>
</title>
<body>
  
<div class="header">
  <img style="clear:both; float:right;" src="http://dinasource.com/swd/images/contentBg.gif"/>
  <div class="wrapper">
      <a style="float:left; margin-top:10px;" href="http:\\www.bits-goa.ac.in">
      <img src="http://dinasource.com/swd/images/BITS_Goa_campus_logo.gif" /></a>
      <p id="pgTitle">Student Welfware Division</p>
    </div>
    <div id="navwrapper">
      <div>
      <ul>
        <% if defined?(current_user.role) %>
          <% Navigation.find_all_by_role(current_user.role).sort_by{|u| u.position}.each do |navigate| %>
          <a href=<%= navigate.link %>> <li><%= navigate.label%></li></a>
          <% end %>
        <% else %>
        <% Navigation.find_all_by_role("general").sort_by{|u| u.position}.each do |navigate| %>
          <a href=<%= navigate.link %>> <li><%= navigate.label%></li></a>
          <% end %>
          <% end %>
        </ul>
    </div>
  </div>
  <!--Header end-->
</div>

<div class="content">
  <div id="banner"><img src="http://qph.is.quoracdn.net/main-qimg-b4ee6903d33c2d6852d7ca304c63caf7" width="1000px"></div>
  <div id="news">
    <div id="newsCon">
      <div id="newsHead">
        <h3>News :</h3>
      </div>
      <div id="newsParaCon">
        <p>oLorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ut dui ac libero hendrerit tempor tempor sit amebulum ven.</p>
      </div>
    </div>
  </div>
  <!--News ends-->
  
  <div class="wrapper">
      <div id="wrapLeft">
        <% if user_signed_in? %>
          <% if( notice.blank? ==false)%>
            <p class="notice HeadLeft"><%= notice %></p>
          <%end%>
        <%end%>

            <%= yield %>
        
      </div>
       <!-- LoggedInCon begin-->
      <div id="wrapRight">
        <% if user_signed_in? %>
        <div class="logggedInCon">
          <div class="Head grey">
            <h3>Hello <span class="thin">
              <%if( current_user.role =="student")%>
                <%=Student.find_by_student_id(current_user.username).name %>
              <%end %>
            </span></h3>
          </div>
          <div id="profImgCon">
            <img src="http://swd.bits-goa.ac.in/css/studentImg/2010C6PS645.jpg" width="145">
          </div>
          <div class="butCon">
    <%=link_to "Sign Out", users_sign_out_path, :method => :delete, :class => "rightBut grey" %>
          </div>
        </div>
        <!-- LoggedInCon ends-->
        <% else %>
        <!-- Login Con begin-->
        <div class="loginCon">
          <div class="Head grey">  

            <h3>Login</h3>
          </div>
          <h4>Enter Login Details:</h4>
          <% if( notice.blank? ==false)%>
          <p class="notice1 HeadLeft"><%= notice %></p>
          <% end %>
          <div id="logLeft">
            <ul>
              <li class="logLeftIn">Username:</li>
              <li class="logLeftIn">Password:</li>
            </ul>
          </div>
          <div id="logRight">
            <form accept-charset="UTF-8" action="/users/sign_in" class="new_user" id="new_user" method="post">
            <div class="logRightIn">
              <input id="user_email"  name="user[username]" size="30" type="text" value="">
            </div>
            <div class="logRightIn">
              <input id="user_password" name="user[password]" size="30" type="password">
            </div>
          </div>
          <div class="butCon">
            <input type="submit" value="LOGIN" class="rightBut grey">
          </div>
        </div>
      </form>
        <!-- Login Con ends-->
        <% end %>
      </div>
    </div>
</div>

<div class="footer">
  <img style="clear:both; float:left;" src="http://dinasource.com/swd/images/contentBg.gif"/>
  <div class="wrapper">
    <div class="footertext">
      <p> Dinasource.com &copy; 2012</p>
      <p><a href="http:\\bits-goa.ac.in">BITS Pilani K.K. Birla Goa Campus</a></p>
      <p><a href="http:\\dinasource.com">Designed &amp; Developed by Dinasource</a></p>
    </div>
      <img style=" float:right; margin: 10px 0 0 0 " src="http://dinasource.com/swd/images/companyBranding.gif" height="75px";/>
  </div>
  
</div>

</body>
<%= yield :bottom %>

</html>